import 'package:get/get.dart';

class Internationalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'filter_category': 'Filter by Category',
      'customer_info': 'Customer Information',
      'country': 'Country',
      'payment_method': 'Payment Method',
      'home': 'Home',
      'orders': 'Orders',
      'search': 'Search',
      'profile': 'Profile',
      'settings': 'Settings',
      'cart': 'Cart',
      'checkout': 'Checkout',
      'billing': 'Billing',
      'name': 'Name',
      'email': 'Email',
      'phone_number': 'Phone Number',
      'billing_address': 'Billing Address',
      'shipping_address': 'Shipping Address',
      'zip_address': 'Zip Address',
      'next': 'Next',
      'cash_on_delivery': 'Cash On Delivery',
      'online_banking': 'Online Banking',
      'credit_debt_card': 'Credit/Debt Card',
      'items': 'Items',
      'tax': 'Tax',
      'delivery': 'Delivery',
      'total': 'Total',
      'shipping_to': 'Shipping to',
      'payment': 'Payment',
      'pay': 'Pay',
      'order_confirmed': 'Order Confirmed',
      'search_products': 'Search Products',
      'password': 'Password',
      'login': 'Login',
      'register': 'Register',
      'google': 'Google',
      'create_account': 'Create Account',
      'register_with_google': 'Register With Google',
      'invalid_input': 'Invalid input',
      'description': 'Description',
      'available_sizes': 'Available Sizes',
      'available_colors': 'Available Colors',
      'confirm_password': 'Confirm Password',
      'language': 'Language',
      'shipping_info': 'Shipping Information',
      'general_settings': 'General Settings',
    },
    'ar_AR': {
      'filter_category': 'تصفية حسب الفئة',
      'customer_info': 'معلومات العميل',
      'country': 'البلد',
      'payment_method': 'طريقة الدفع',
      'home': 'الصفحة الرئيسية',
      'orders': 'الطلبات',
      'search': 'بحث',
      'profile': 'الملف الشخصي',
      'settings': 'الإعدادات',
      'cart': 'عربة التسوق',
      'checkout': 'الدفع',
      'billing': 'الفوترة',
      'name': 'الإسم',
      'email': 'البريد الإلكتروني',
      'phone_number': 'رقم الهاتف',
      'billing_address': 'عنوان الفوترة',
      'shipping_address': 'عنوان الشحن',
      'zip_address': 'الرمز البريدي',
      'next': 'التالي',
      'cash_on_delivery': 'الدفع عند الإستلام',
      'online_banking': 'الإتصال المصرفي عبر الإنترنت',
      'credit_debt_card': 'الدفع ببطاقة الائتمان/الدين',
      'items': 'العناصر',
      'tax': 'الضرائب',
      'delivery': 'التسليم',
      'total': 'المجموع',
      'shipping_to': 'الشحن إلى',
      'payment': 'الدفع',
      'pay': 'دفع',
      'order_confirmed': 'تأكيد الطلب',
      'search_products': 'البحث عن المنتجات',
      'password': 'كلمة المرور',
      'login': 'تسجيل الدخول',
      'register': 'التسجيل',
      'google': 'جوجل',
      'create_account': 'إنشاء حساب',
      'register_with_google': 'التسجيل مع جو',
      'invalid_input': 'إدخال غير صحيح',
      'description': 'وصف',
      'available_sizes': 'الأحجام المتوفرة',
      'available_colors': 'الألوان المتاحة',
      'language': 'لغة',
      'shipping_info': 'معلومات الشحن',
      'general_settings': 'الاعدادات العامة',
    }
  };
}